#!/usr/bin/env php
<?php

declare(strict_types=1);

/*
 * This file is part of the community-maintained Playwright PHP project.
 * It is not affiliated with or endorsed by Microsoft.
 *
 * (c) 2025-Present - Playwright PHP - https://github.com/playwright-php
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Playwright\Symfony\Tests\Fixtures\App\TestKernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

require dirname(__DIR__, 3).'/vendor/autoload.php';

$kernel = new TestKernel('test', false);
$application = new Application($kernel);

$application->run();
